//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMSAPP.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public int productid { get; set; }
        public string productname { get; set; }
        public Nullable<decimal> price { get; set; }
        public string description { get; set; }
        public Nullable<int> categoryid { get; set; }
    
        public virtual category category { get; set; }
    }
}
